apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-service
  template:
    metadata:
      labels:
        app: cloud-service
    spec:
      containers:
        - name: cloud-service
          image: frankfromcn/cloud-service:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-service-service
spec:
  selector:
    app: cloud-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080
