name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 检出代码
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. 设置 Docker 登陆
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. 构建并推送镜像
#    - name: Build and Push Docker Image
#      run: |
#        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .
#        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

    # 4. 配置 kubectl
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    # 5. 配置 kubeconfig
    - name: Configure kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig
        export KUBECONFIG=kubeconfig
        kubectl apply -f kubernetes/release/.
#       kubectl rollout status deployment/my-app
